#!/bin/bash

echo "-----------------------"
echo "Start Nearde IDE ..."
echo "-----------------------"

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

APP_HOME=$(dirname "$(realpath "$0")")
cd "$APP_HOME"
exec java -jar "$APP_HOME/NeardeLauncher.jar"
